exports.defaultHtmlHeadInjectDataKeys = [
  "APP_ROOT",
  "NEW_RELIC_BROWSER_ID",
  "NEW_RELIC_BROWSER_KEY",
  "PRODUCT_SERVICE_ENV_URL",
  "PRODUCT_ENV_URL",
  "FIREBASE_API_KEY",
  "FIREBASE_AUTH_DOMAIN",
  "FIREBASE_PROJECT_ID",
  "FIREBASE_STORAGE_BUCKET",
  "FIREBASE_MESSAGING_SENDER_ID",
  "FIREBASE_APP_ID",
  "FIREBASE_MEASUREMENT_ID",
];
